// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../tests/mocks/mcp_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mcp "github.com/inference-gateway/inference-gateway/mcp"
	gomock "go.uber.org/mock/gomock"
)

// MockMCPClientInterface is a mock of MCPClientInterface interface.
type MockMCPClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMCPClientInterfaceMockRecorder
	isgomock struct{}
}

// MockMCPClientInterfaceMockRecorder is the mock recorder for MockMCPClientInterface.
type MockMCPClientInterfaceMockRecorder struct {
	mock *MockMCPClientInterface
}

// NewMockMCPClientInterface creates a new mock instance.
func NewMockMCPClientInterface(ctrl *gomock.Controller) *MockMCPClientInterface {
	mock := &MockMCPClientInterface{ctrl: ctrl}
	mock.recorder = &MockMCPClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPClientInterface) EXPECT() *MockMCPClientInterfaceMockRecorder {
	return m.recorder
}

// ExecuteTool mocks base method.
func (m *MockMCPClientInterface) ExecuteTool(ctx context.Context, request mcp.Request, serverURL string) (mcp.CallToolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTool", ctx, request, serverURL)
	ret0, _ := ret[0].(mcp.CallToolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTool indicates an expected call of ExecuteTool.
func (mr *MockMCPClientInterfaceMockRecorder) ExecuteTool(ctx, request, serverURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTool", reflect.TypeOf((*MockMCPClientInterface)(nil).ExecuteTool), ctx, request, serverURL)
}

// GetServerCapabilities mocks base method.
func (m *MockMCPClientInterface) GetServerCapabilities() map[string]mcp.ServerCapabilities {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerCapabilities")
	ret0, _ := ret[0].(map[string]mcp.ServerCapabilities)
	return ret0
}

// GetServerCapabilities indicates an expected call of GetServerCapabilities.
func (mr *MockMCPClientInterfaceMockRecorder) GetServerCapabilities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerCapabilities", reflect.TypeOf((*MockMCPClientInterface)(nil).GetServerCapabilities))
}

// InitializeAll mocks base method.
func (m *MockMCPClientInterface) InitializeAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeAll indicates an expected call of InitializeAll.
func (mr *MockMCPClientInterfaceMockRecorder) InitializeAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeAll", reflect.TypeOf((*MockMCPClientInterface)(nil).InitializeAll), ctx)
}

// IsInitialized mocks base method.
func (m *MockMCPClientInterface) IsInitialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInitialized indicates an expected call of IsInitialized.
func (mr *MockMCPClientInterfaceMockRecorder) IsInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialized", reflect.TypeOf((*MockMCPClientInterface)(nil).IsInitialized))
}
