version: '2'
linters:
  enable:
    - gocritic
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/stretchr/testify)
        - prefix(github.com/inference-gateway/inference-gateway/tests/mocks)
        - default
        - prefix(github.com/inference-gateway/)
        - prefix(github.com/inference-gateway/inference-gateway)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
