services:
  inference-gateway:
    build:
      context: ../../..
      dockerfile: Dockerfile
    pull_policy: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      A2A_ENABLE: 'true'
      A2A_EXPOSE: 'true'
      A2A_AGENTS: 'http://weather-agent:8080,http://helloworld-agent:8080,http://calculator-agent:8080,http://google-calendar-agent:8080'
    networks:
      - a2a-network

  helloworld-agent:
    build:
      context: ./helloworld-agent
      dockerfile: Dockerfile
    environment:
      A2A_AGENT_URL: 'http://helloworld-agent:8080'
      A2A_AGENT_CLIENT_PROVIDER: 'deepseek'
      A2A_AGENT_CLIENT_MODEL: 'deepseek-chat'
      A2A_AGENT_CLIENT_BASE_URL: 'http://inference-gateway:8080/v1'
    ports:
      - '8081:8080'
    networks:
      - a2a-network

  calculator-agent:
    build:
      context: ./calculator-agent
      dockerfile: Dockerfile
    environment:
      A2A_AGENT_URL: 'http://calculator-agent:8080'
      A2A_AGENT_CLIENT_PROVIDER: 'deepseek'
      A2A_AGENT_CLIENT_MODEL: 'deepseek-chat'
      A2A_AGENT_CLIENT_BASE_URL: 'http://inference-gateway:8080/v1'
    ports:
      - '8082:8080'
    networks:
      - a2a-network

  weather-agent:
    build:
      context: ./weather-agent
      dockerfile: Dockerfile
    environment:
      A2A_AGENT_URL: 'http://weather-agent:8080'
      A2A_AGENT_CLIENT_PROVIDER: 'deepseek'
      A2A_AGENT_CLIENT_MODEL: 'deepseek-chat'
      A2A_AGENT_CLIENT_BASE_URL: 'http://inference-gateway:8080/v1'
    ports:
      - '8083:8080'
    networks:
      - a2a-network

  google-calendar-agent:
    image: ghcr.io/inference-gateway/google-calendar-agent:latest
    pull_policy: always
    environment:
      A2A_AGENT_URL: 'http://google-calendar-agent:8080'
      A2A_AGENT_CLIENT_PROVIDER: 'deepseek'
      A2A_AGENT_CLIENT_MODEL: 'deepseek-chat'
      A2A_AGENT_CLIENT_BASE_URL: 'http://inference-gateway:8080/v1'
    env_file:
      - .env.google
    ports:
      - '8084:8080'
    networks:
      - a2a-network

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --config
      - /config/.a2a.yaml
    command:
      - config
      - set
      - server-url
      - http://helloworld-agent:8080
    volumes:
      - ./config:/config
    networks:
      - a2a-network

networks:
  a2a-network:
