services:
  inference-gateway:
    build:
      context: ../../..
      dockerfile: Dockerfile
    pull_policy: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      A2A_ENABLE: "true"
      A2A_EXPOSE: "true"
      A2A_AGENTS: "http://helloworld-agent:8080,http://calculator-agent:8080,http://weather-agent:8080,http://google-calendar-agent:8080"
    depends_on:
      healthchecker:
        condition: service_healthy
    networks:
      - a2a-network

  helloworld-agent:
    build:
      context: ./helloworld-agent
      dockerfile: Dockerfile
    environment:
      DEBUG: "true"
      INFERENCE_GATEWAY_URL: "http://inference-gateway:8080/v1"
      LLM_PROVIDER: "cohere"
      LLM_MODEL: "command-r"
    ports:
      - "8081:8080"
    networks:
      - a2a-network

  calculator-agent:
    build:
      context: ./calculator-agent
      dockerfile: Dockerfile
    environment:
      DEBUG: "true"
      INFERENCE_GATEWAY_URL: "http://inference-gateway:8080/v1"
      LLM_PROVIDER: "deepseek"
      LLM_MODEL: "deepseek-chat"
    ports:
      - "8082:8080"
    networks:
      - a2a-network

  weather-agent:
    build:
      context: ./weather-agent
      dockerfile: Dockerfile
    environment:
      DEBUG: "true"
      INFERENCE_GATEWAY_URL: "http://inference-gateway:8080/v1"
      LLM_PROVIDER: "deepseek"
      LLM_MODEL: "deepseek-chat"
    ports:
      - "8083:8080"
    networks:
      - a2a-network

  google-calendar-agent:
    image: ghcr.io/inference-gateway/google-calendar-agent:latest
    pull_policy: always
    env_file:
      - .env.google
    networks:
      - a2a-network

  healthchecker:
    build:
      context: .
      dockerfile: Dockerfile.healthchecker
    depends_on:
      helloworld-agent:
        condition: service_started
      calculator-agent:
        condition: service_started
      weather-agent:
        condition: service_started
      google-calendar-agent:
        condition: service_started
    healthcheck:
      test:
        - CMD
        - "/healthcheck.sh"
      interval: 300s
      timeout: 15s
      retries: 3
      start_period: 60s
    networks:
      - a2a-network

networks:
  a2a-network:
