---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
# ---
# # For production, you might use Let's Encrypt:
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-production
# spec:
#   acme:
#     server: https://acme-production-v02.api.letsencrypt.org/directory
#     email: your-email@example.com
#     privateKeySecretRef:
#       name: letsencrypt-production
#     solvers:
#       - http01:
#           ingress:
#             class: nginx
