---
version: "3"

tasks:
  deploy-infrastructure:
    desc: "Deploy TLS infrastructure"
    cmds:
      - ctlptl apply -f Cluster.yaml
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - helm repo add jetstack https://charts.jetstack.io
      - echo "🚀 Starting TLS infrastructure deployment..."
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace kube-system \
          --set controller.progressDeadlineSeconds=500 \
          --version 4.12.2 \
          --wait \
          ingress-nginx ingress-nginx/ingress-nginx
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace cert-manager \
          --version 1.17.2 \
          --set crds.enabled=true \
          --wait \
          cert-manager jetstack/cert-manager
      - kubectl apply -f cert-manager/
      - echo "🔒 TLS infrastructure deployed successfully!"

  deploy-inference-gateway:
    desc: "Deploy inference-gateway with TLS"
    cmds:
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace inference-gateway \
          --set ingress.enabled=true \
          --set ingress.annotations."cert-manager\.io/cluster-issuer"=selfsigned-issuer \
          --set ingress.hosts[0].host=api.inference-gateway.local \
          --set ingress.hosts[0].paths[0].path=/ \
          --set ingress.hosts[0].paths[0].pathType=ImplementationSpecific \
          --set ingress.tls.enabled=true \
          --set ingress.tls.hosts[0]=api.inference-gateway.local \
          --set ingress.tls.secretName=api-inference-gateway-local-tls \
          --version 0.7.1 \
          --wait \
          inference-gateway oci://ghcr.io/inference-gateway/charts/inference-gateway
      - echo "🔐 Inference Gateway with TLS deployed successfully!"

  clean:
    desc: "Clean up the cluster"
    cmds:
      - ctlptl delete -f Cluster.yaml
      - echo "🧹 Cluster cleaned up successfully!"
