---
version: "3"

tasks:
  deploy-infrastructure:
    desc: "Deploy TLS infrastructure"
    cmds:
      - ctlptl apply -f Cluster.yaml
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - helm repo add jetstack https://charts.jetstack.io
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace kube-system \
          --version 4.12.1 \
          ingress-nginx ingress-nginx/ingress-nginx
      - kubectl apply -f cert-manager/

  deploy-inference-gateway:
    desc: "Deploy inference-gateway with TLS"
    cmds:
      - kubectl create ns inference-gateway -o yaml --dry-run=client | kubectl apply --server-side -f -
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace inference-gateway \
          --set ingress.enabled=true \
          --set ingress.tls[0].hosts[0]="api.inference-gateway.local" \
          --set ingress.tls[0].secretName="api-inference-gateway-tls" \
          inference-gateway oci://ghcr.io/inference-gateway/charts/inference-gateway:latest

  clean:
    desc: "Clean up the cluster"
    cmds:
      - ctlptl delete -f Cluster.yaml
