apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-gateway.fullname" . }}-defaults
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
data:
  # General settings
  ENVIRONMENT: {{ .Values.config.ENVIRONMENT | quote }}
  ENABLE_TELEMETRY: {{ .Values.config.ENABLE_TELEMETRY | quote }}
  ENABLE_AUTH: {{ .Values.config.ENABLE_AUTH | quote }}
  ALLOWED_MODELS: {{ .Values.config.ALLOWED_MODELS | quote }}
  # Model Context Protocol (MCP)
  MCP_ENABLE: {{ .Values.config.MCP_ENABLE | quote }}
  MCP_EXPOSE: {{ .Values.config.MCP_EXPOSE | quote }}
  MCP_SERVERS: {{ .Values.config.MCP_SERVERS | quote }}
  MCP_CLIENT_TIMEOUT: {{ .Values.config.MCP_CLIENT_TIMEOUT | quote }}
  MCP_DIAL_TIMEOUT: {{ .Values.config.MCP_DIAL_TIMEOUT | quote }}
  MCP_TLS_HANDSHAKE_TIMEOUT: {{ .Values.config.MCP_TLS_HANDSHAKE_TIMEOUT | quote }}
  MCP_RESPONSE_HEADER_TIMEOUT: {{ .Values.config.MCP_RESPONSE_HEADER_TIMEOUT | quote }}
  MCP_EXPECT_CONTINUE_TIMEOUT: {{ .Values.config.MCP_EXPECT_CONTINUE_TIMEOUT | quote }}
  MCP_REQUEST_TIMEOUT: {{ .Values.config.MCP_REQUEST_TIMEOUT | quote }}
  # Agent-to-Agent (A2A) Protocol
  A2A_ENABLE: {{ .Values.config.A2A_ENABLE | quote }}
  A2A_EXPOSE: {{ .Values.config.A2A_EXPOSE | quote }}
  A2A_AGENTS: {{ .Values.config.A2A_AGENTS | quote }}
  A2A_CLIENT_TIMEOUT: {{ .Values.config.A2A_CLIENT_TIMEOUT | quote }}
  A2A_POLLING_ENABLE: {{ .Values.config.A2A_POLLING_ENABLE | quote }}
  A2A_POLLING_INTERVAL: {{ .Values.config.A2A_POLLING_INTERVAL | quote }}
  A2A_POLLING_TIMEOUT: {{ .Values.config.A2A_POLLING_TIMEOUT | quote }}
  A2A_MAX_POLL_ATTEMPTS: {{ .Values.config.A2A_MAX_POLL_ATTEMPTS | quote }}
  # OpenID Connect
  OIDC_ISSUER_URL: {{ .Values.config.OIDC_ISSUER_URL | quote }}
  # Server settings
  SERVER_HOST: {{ .Values.config.SERVER_HOST | quote }}
  SERVER_PORT: {{ .Values.config.SERVER_PORT | quote }}
  SERVER_READ_TIMEOUT: {{ .Values.config.SERVER_READ_TIMEOUT | quote }}
  SERVER_WRITE_TIMEOUT: {{ .Values.config.SERVER_WRITE_TIMEOUT | quote }}
  SERVER_IDLE_TIMEOUT: {{ .Values.config.SERVER_IDLE_TIMEOUT | quote }}
  SERVER_TLS_CERT_PATH: {{ .Values.config.SERVER_TLS_CERT_PATH | quote }}
  SERVER_TLS_KEY_PATH: {{ .Values.config.SERVER_TLS_KEY_PATH | quote }}
  # Client settings
  CLIENT_TIMEOUT: {{ .Values.config.CLIENT_TIMEOUT | quote }}
  CLIENT_MAX_IDLE_CONNS: {{ .Values.config.CLIENT_MAX_IDLE_CONNS | quote }}
  CLIENT_MAX_IDLE_CONNS_PER_HOST: {{ .Values.config.CLIENT_MAX_IDLE_CONNS_PER_HOST | quote }}
  CLIENT_IDLE_CONN_TIMEOUT: {{ .Values.config.CLIENT_IDLE_CONN_TIMEOUT | quote }}
  CLIENT_TLS_MIN_VERSION: {{ .Values.config.CLIENT_TLS_MIN_VERSION | quote }}
  CLIENT_DISABLE_COMPRESSION: {{ .Values.config.CLIENT_DISABLE_COMPRESSION | quote }}
  CLIENT_RESPONSE_HEADER_TIMEOUT: {{ .Values.config.CLIENT_RESPONSE_HEADER_TIMEOUT | quote }}
  CLIENT_EXPECT_CONTINUE_TIMEOUT: {{ .Values.config.CLIENT_EXPECT_CONTINUE_TIMEOUT | quote }}
  # Providers
  ANTHROPIC_API_URL: {{ .Values.config.ANTHROPIC_API_URL | quote }}
  CLOUDFLARE_API_URL: {{ .Values.config.CLOUDFLARE_API_URL | quote }}
  COHERE_API_URL: {{ .Values.config.COHERE_API_URL | quote }}
  GROQ_API_URL: {{ .Values.config.GROQ_API_URL | quote }}
  OLLAMA_API_URL: {{ .Values.config.OLLAMA_API_URL | quote }}
  OPENAI_API_URL: {{ .Values.config.OPENAI_API_URL | quote }}
  DEEPSEEK_API_URL: {{ .Values.config.DEEPSEEK_API_URL | quote }}
