apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envFrom.configMapRef }}
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
data:
  {{- if .Values.config }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
