apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "inference-gateway.fullname" .) }}
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
data:
  {{- if .Values.config }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
