{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "inference-gateway.fullname" . }}
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName | quote }}
  {{- with .Values.gateway.addresses }}
  addresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.infrastructure }}
  infrastructure:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name | quote }}
      {{- with .hostname }}
      hostname: {{ . | quote }}
      {{- end }}
      port: {{ .port }}
      protocol: {{ .protocol | quote }}
      {{- with .tls }}
      tls:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .allowedRoutes }}
      allowedRoutes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
