{{- if .Values.monitoring.grafana.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated.monitoring:9090
    isDefault: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"
{{- end }}
