apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inference-gateway.fullname" . }}-defaults
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
stringData:
  # OpenID Connect
  OIDC_CLIENT_ID: ""
  OIDC_CLIENT_SECRET: ""
  # Providers
  ANTHROPIC_API_KEY: ""
  CLOUDFLARE_API_KEY: ""
  COHERE_API_KEY: ""
  GROQ_API_KEY: ""
  OLLAMA_API_KEY: ""
  OPENAI_API_KEY: ""
  DEEPSEEK_API_KEY: ""
