{{- if .Values.envFrom.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envFrom.secretRef }}
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
stringData: {}
{{- end }}
