{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inference-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      {{- include "inference-gateway.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchLabels:
      monitoring: "true"
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    honorLabels: true
{{- end }}
