---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: k3d
name: k3d-mcp-cluster
k3d:
  v1alpha5Simple:
    agents: 1
    image: docker.io/rancher/k3s:v1.32.0-k3s1
    ports:
      - port: 80:80
        nodeFilters:
          - server:0
    options:
      k3s:
        extraArgs:
          - arg: --disable=traefik
            nodeFilters:
              - server:0
