---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: k3d
k3d:
  v1alpha5Simple:
    agents: 3
    image: docker.io/rancher/k3s:v1.32.0-k3s1
    options:
      k3s:
        extraArgs:
          - arg: --disable=traefik
            nodeFilters:
              - server:0
