---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: inference-gateway
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: 'true'
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
  retention: 24h
  version: v3.2.1
  enableAdminAPI: false
