---
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: local-registry
port: 5000
image: registry:2
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: k3d
registry: local-registry
k3d:
  v1alpha5Simple:
    agents: 1
    image: docker.io/rancher/k3s:v1.32.0-k3s1
    options:
      k3s:
        extraArgs:
          - arg: --disable=traefik
            nodeFilters:
              - server:0
