---
version: "3"

tasks:
  deploy-infrastructure:
    desc: "Deploy basic infrastructure"
    cmds:
      - ctlptl apply -f Cluster.yaml
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace kube-system \
          --version 4.12.1 \
          --wait \
          ingress-nginx ingress-nginx/ingress-nginx

  deploy-inference-gateway:
    desc: "Deploy inference-gateway with helm"
    cmds:
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace inference-gateway \
          --set ingress.enabled=true \
          --wait \
          inference-gateway oci://ghcr.io/inference-gateway/charts/inference-gateway:latest

  clean:
    desc: "Clean up the cluster"
    cmds:
      - ctlptl delete -f Cluster.yaml
