---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logs-analyzer-role
rules:
  - apiGroups: ['']
    resources: ['namespaces', 'pods', 'pods/log']
    verbs: ['list', 'get']
