---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      serviceAccountName: ollama
      containers:
        - name: ollama-model
          image: ollama/ollama:0.6.5
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ollama
          resources:
            limits:
              cpu: 3000m
              memory: 6500Mi
            requests:
              cpu: 2000m
              memory: 4600Mi
          volumeMounts:
            - name: ollama-models-store
              mountPath: /root/.ollama/models
        - name: ollama-model-puller
          image: ollama/ollama:0.6.5
          command:
            - bash
          args:
            - -c
            - "ollama pull deepseek-r1:1.5b && tail -f /dev/null"
          envFrom:
            - configMapRef:
                name: ollama
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: ollama-models-store
          emptyDir: {}
