---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inference-gateway-tls
  namespace: inference-gateway
spec:
  secretName: inference-gateway-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: api.inference-gateway.local
  dnsNames:
    - api.inference-gateway.local
    - inference-gateway.inference-gateway.svc.cluster.local
