---
version: "3"

tasks:
  deploy-infrastructure:
    desc: "Deploy hybrid infrastructure"
    cmds:
      - ctlptl apply -f Cluster.yaml
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace kube-system \
          --version 4.12.1 \
          --wait \
          ingress-nginx ingress-nginx/ingress-nginx
      - kubectl create namespace ollama -o yaml --dry-run=client | kubectl apply -f -
      - kubectl apply -f ollama/
      - kubectl -n ollama rollout status deployment ollama

  deploy-inference-gateway:
    desc: "Deploy inference-gateway with hybrid providers"
    cmds:
      - |
        helm upgrade --install \
          --create-namespace \
          --namespace inference-gateway \
          --set ingress.enabled=true \
          --set config.OLLAMA_API_URL="http://ollama.ollama:8080/v1" \
          --wait \
          inference-gateway oci://ghcr.io/inference-gateway/charts/inference-gateway:latest

  clean:
    desc: "Clean up the cluster"
    cmds:
      - ctlptl delete -f Cluster.yaml
