---
services:
  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-development}
      MCP_ENABLE: ${MCP_ENABLE:-true}
      MCP_EXPOSE: ${MCP_EXPOSE:-true}
      MCP_SERVERS: ${MCP_SERVERS:-http://mcp-time-server:8081/mcp,http://mcp-search-server:8082/mcp,http://mcp-filesystem-server:8083/mcp,http://mcp-pizza-server:8084/mcp}
    depends_on:
      mcp-time-server:
        condition: service_healthy
      mcp-search-server:
        condition: service_healthy
      mcp-filesystem-server:
        condition: service_healthy
      mcp-pizza-server:
        condition: service_healthy
    networks:
      - mcp-network

  mcp-inspector:
    image: node:lts
    working_dir: /app
    command: >
      sh -c "npx -y @modelcontextprotocol/inspector"
    ports:
      - "6274:6274"
      - "6277:6277"
    environment:
      LOG_LEVEL: debug
      HOST: 0.0.0.0
      MCP_SERVER_URL: http://mcp-time-server:8081/mcp,http://mcp-search-server:8082/mcp,http://mcp-filesystem-server:8083/mcp,http://mcp-pizza-server:8084/mcp
    networks:
      - mcp-network
    depends_on:
      mcp-time-server:
        condition: service_healthy
      mcp-search-server:
        condition: service_healthy
      mcp-filesystem-server:
        condition: service_healthy
      mcp-pizza-server:
        condition: service_healthy

  mcp-time-server:
    build:
      context: ./time-server
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network

  mcp-search-server:
    build:
      context: ./search-server
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network

  mcp-filesystem-server:
    build:
      context: ./filesystem-server
      dockerfile: Dockerfile
    volumes:
      - ./filesystem-data:/tmp/mcp-files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network

  mcp-pizza-server:
    build:
      context: ./pizza-server
      dockerfile: Dockerfile
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://localhost:8084/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
