---
apiVersion: v1
kind: Namespace
metadata:
  name: agents
  labels:
    inference-gateway.com/managed: 'true'
---
apiVersion: core.inference-gateway.com/v1alpha1
kind: A2AServer
metadata:
  name: a2a-server-email-agent
  namespace: agents
  labels:
    inference-gateway.ai/a2a-agent: 'true'
  annotations:
    inference-gateway.ai/agent-type: 'email'
    inference-gateway.ai/service-labels: 'inference-gateway.ai/a2a-agent=true'
spec:
  image: 'ghcr.io/inference-gateway/email-agent:latest'
  timezone: 'CET'
  port: 8080
  host: '0.0.0.0'
  readTimeout: '30s'
  writeTimeout: '30s'
  idleTimeout: '60s'
  logging:
    level: 'info'
    format: 'json'
  telemetry:
    enabled: true
    port: 9090
  queue:
    enabled: true
    maxSize: 1000
    cleanupInterval: '5m'
  tls:
    enabled: false
    secretRef: ''
  agent:
    enabled: true
    tls:
      enabled: true
      secretRef: ''
    maxConversationHistory: 10
    maxChatCompletionIterations: 5
    maxRetries: 3
    apiKey:
      secretRef:
        name: email-agent-secrets
        key: DEEPSEEK_API_KEY
    llm:
      model: 'deepseek/deepseek-agent'
      maxTokens: 4096
      temperature: 0.7
      customHeaders:
        - name: 'User-Agent'
          value: 'Email Agent'
      systemPrompt: 'You are a helpful assistant for managing Email communications. You can send, read, and manage emails, and you can also handle attachments and email threads.'
---
apiVersion: v1
kind: Secret
metadata:
  name: email-agent-secrets
  namespace: agents
type: Opaque
stringData:
  DEEPSEEK_API_KEY: ''
