---
apiVersion: v1
kind: Namespace
metadata:
  name: agents
  labels:
    inference-gateway.com/managed: 'true'
---
apiVersion: core.inference-gateway.com/v1alpha1
kind: A2AServer
metadata:
  name: a2a-server-google-calendar-agent
  namespace: agents
  labels:
    inference-gateway.ai/a2a-agent: 'true'
  annotations:
    inference-gateway.ai/agent-type: 'google-calendar'
    inference-gateway.ai/service-labels: 'inference-gateway.ai/a2a-agent=true'
spec:
  image: 'ghcr.io/inference-gateway/google-calendar-agent:latest'
  timezone: 'CET'
  port: 8080
  host: '0.0.0.0'
  readTimeout: '30s'
  writeTimeout: '30s'
  idleTimeout: '60s'
  logging:
    level: 'info'
    format: 'json'
  telemetry:
    enabled: true
    port: 9090
  queue:
    enabled: true
    maxSize: 1000
    cleanupInterval: '5m'
  tls:
    enabled: true
    secretRef: 'google-calendar-agent-tls'
  agent:
    enabled: true
    envFrom:
      - secretRef:
          name: google-calendar-agent-service-account
    maxConversationHistory: 10
    maxChatCompletionIterations: 5
    maxRetries: 3
    apiKey:
      secretRef:
        name: google-calendar-internal-agent
        key: DEEPSEEK_API_KEY
    llm:
      model: 'deepseek/deepseek-agent'
      maxTokens: 4096
      temperature: 0.7
      customHeaders:
        - name: 'User-Agent'
          value: 'Google Calendar Agent'
      systemPrompt: 'You are a helpful assistant for managing Google Calendar events. You can create, read, update, and delete events, and you can also list upcoming events.'
---
apiVersion: v1
kind: Secret
metadata:
  name: google-calendar-internal-agent
  namespace: agents
type: Opaque
stringData:
  DEEPSEEK_API_KEY: ''
---
apiVersion: v1
kind: Secret
metadata:
  name: google-calendar-agent-service-account
  namespace: agents
type: Opaque
stringData:
  GOOGLE_CALENDAR_SA_JSON: ''
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: google-calendar-agent-tls
  namespace: agents
spec:
  dnsNames:
    - google-calendar-agent.agents.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: google-calendar-agent-tls
  usages:
    - digital signature
    - key encipherment
