name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: "1.23"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.64.7

      - name: Install Mockgen
        run: go install go.uber.org/mock/mockgen@v0.5.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Validate OpenAPI with Spectral
        run: spectral lint openapi.yaml

      - name: Install dependencies
        run: go mod tidy

      - name: Run generate
        run: go generate ./providers/... ./api/... ./otel/...

      - name: Check dirty
        run: git diff --exit-code

      - name: Run Lint
        run: golangci-lint run

      - name: Build
        run: go build -o bin/inference-gateway cmd/gateway/main.go

      - name: Test
        run: go test -v ./...

      - name: Benchmark
        run: go test -bench=. -run=^$ -benchmem -benchtime=100x -count=20 ./tests/...
